# Generated by Django 4.1.5 on 2023-01-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='permit',
            new_name='permis',
        ),
    ]
