# Generated by Django 4.1.5 on 2023-01-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0002_rename_permit_user_permis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Pin',
        ),
        migrations.AddField(
            model_name='car',
            name='Pin',
            field=models.IntegerField(default=0),
        ),
    ]
