# Generated by Django 4.1.5 on 2023-02-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0003_remove_reservation_pin_car_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_car_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='image_mark_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
